name: Bug
description: An unexpected problem or behavior
type: Bug
body:
  - type: textarea
    id: what
    attributes:
      label: What happened
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What you expected instead
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Customer, tenant, environment name or version.
    validations:
      required: false
